name: metro
description: "Aplicativo de monitoramento automatizado de obras do Metrô de São Paulo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  
  # State Management
  provider: ^6.1.2
  
  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  
  # Location
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  
  # Maps
  google_maps_flutter: ^2.9.0
  
  # Date/Time
  intl: ^0.19.0
  
  # HTTP & API
  http: ^1.2.2
  google_generative_ai: ^0.4.6
  
  # File Handling
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  
  # Permissions
  permission_handler: ^11.3.1
  
  # UI Components
  flutter_slidable: ^3.1.1
  shimmer: ^3.0.0
  
  # Charts & Visualization
  fl_chart: ^0.69.0
  
  # Utils
  uuid: ^4.5.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

