// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQBgd7ZmXOctxiDAh4qHl_ySiMN_qVPxE',
    appId: '1:210888569709:web:a5f76244f112758430e064',
    messagingSenderId: '210888569709',
    projectId: 'metro-31d1d',
    authDomain: 'metro-31d1d.firebaseapp.com',
    storageBucket: 'metro-31d1d.firebasestorage.app',
    measurementId: 'G-X0QVVQ0BWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi3on3lUW_tTofjsQ-P9qihqZzy5ipMVg',
    appId: '1:210888569709:android:aa437d2869eec59430e064',
    messagingSenderId: '210888569709',
    projectId: 'metro-31d1d',
    storageBucket: 'metro-31d1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWV8f8v8b2Bcge1ZgedUB1ERjkwVeHjmg',
    appId: '1:210888569709:ios:cf96c21aa269810830e064',
    messagingSenderId: '210888569709',
    projectId: 'metro-31d1d',
    storageBucket: 'metro-31d1d.firebasestorage.app',
    iosBundleId: 'com.pii.metro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWV8f8v8b2Bcge1ZgedUB1ERjkwVeHjmg',
    appId: '1:210888569709:ios:cf96c21aa269810830e064',
    messagingSenderId: '210888569709',
    projectId: 'metro-31d1d',
    storageBucket: 'metro-31d1d.firebasestorage.app',
    iosBundleId: 'com.pii.metro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQBgd7ZmXOctxiDAh4qHl_ySiMN_qVPxE',
    appId: '1:210888569709:web:749826634f7c8cb730e064',
    messagingSenderId: '210888569709',
    projectId: 'metro-31d1d',
    authDomain: 'metro-31d1d.firebaseapp.com',
    storageBucket: 'metro-31d1d.firebasestorage.app',
    measurementId: 'G-7M5L92TJQD',
  );

}